name: Hello World Concurrent

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: |
          echo "one"
          echo "two"
  hello1:
    runs-on: ubuntu-latest
    needs: hello

    steps:
      - name: Hello Step
        run: |
          echo "one"
          echo "two"
  hello3:
    runs-on: ubuntu-latest
    needs: hello1

    steps:
      - name: Hello Step
        run: |
          echo "one"
          echo "two"          
